export const GENRES = [
  { label: 'All Music Genres', value: null },
  { label: 'Alternative Rock', value: 'alternativerock' },
  { label: 'Ambient', value: 'ambient' },
  { label: 'Classical', value: 'classical' },
  { label: 'Country', value: 'country' },
  { label: 'Dance & EDM', value: 'danceedm' },
  { label: 'Dancehall', value: 'dancehall' },
  { label: 'Deep House', value: 'deephouse' },
  { label: 'Disco', value: 'disco' },
  { label: 'Drum & Bass', value: 'drumbass' },
  { label: 'Dubstep', value: 'dubstep' },
  { label: 'Electronic', value: 'electronic' },
  { label: 'Folk & Singer-Songwriter', value: 'folksingersongwriter' },
  { label: 'Hip-hop & Rap', value: 'hiphoprap' },
  { label: 'House', value: 'house' },
  { label: 'Indie', value: 'indie' },
  { label: 'Jazz & Blues', value: 'jazzblues' },
  { label: 'Latin', value: 'latin' },
  { label: 'Metal', value: 'metal' },
  { label: 'Piano', value: 'piano' },
  { label: 'Pop', value: 'pop' },
  { label: 'R&B & Soul', value: 'rbsoul' },
  { label: 'Reggae', value: 'reggae' },
  { label: 'Reggaeton', value: 'reggaeton' },
  { label: 'Rock', value: 'rock' },
  { label: 'Soundtrack', value: 'soundtrack' },
  { label: 'Techno', value: 'techno' },
  { label: 'Trance', value: 'trance' },
  { label: 'Trap', value: 'trap' },
  { label: 'Triphop', value: 'triphop' },
  { label: 'World', value: 'world' },
]
